/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Main.Main;
import Report.Report_DetailReport;
import Report.Report_ExceptionReport;
import Report.Report_SummaryReport;
import Report.Report_Top_3_Sold;
import Report.Report_Top_3_outcome;
import static Interface.Interface_Payment.getScaledImage;


import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author ITSUKA KOTORI
 */
public class Interface_Report extends javax.swing.JFrame {

    private Date start_date, end_date;
    /**
     * Creates new form Interface_Report
     */
    public Interface_Report() {
        initComponents();        
        initComponents_SetClose();
        initComponents_Interface();
        this.setIconImage(Main.DEFUALT_ICON.getImage());
    }

    private void initComponents_Interface() {
        setTitle("Report Generator");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.jLabel1.setIcon(new ImageIcon(getScaledImage(new ImageIcon("resource/neon.png").getImage(), 254, 75)));
        this.today_date_label.setText("Today Date : " + Main.DATE_FORMAT.format(Main.getToday_date()));
        set_start_end();
    }
    private void initComponents_SetClose(){
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                new Interface_MenuManager().setVisible(true);
            }
        });
    }

    public final void set_start_end(){
        Calendar xx = Calendar.getInstance();
        xx.setTime(new Date());
        xx.set(Calendar.DAY_OF_MONTH, 1);
        start_date = new Date();
        start_date = xx.getTime();
        xx.add(Calendar.MONTH, 1);
        xx.set(Calendar.DAY_OF_MONTH, 1);
        xx.add(Calendar.DATE, -1);
        end_date = new Date();
        end_date = xx.getTime();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_html = new javax.swing.JLabel();
        report_panel = new javax.swing.JPanel();
        html_other_label = new javax.swing.JLabel();
        graph_destination = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detail_report = new javax.swing.JButton();
        exception_top_sales = new javax.swing.JButton();
        back_to_menu = new javax.swing.JButton();
        summary_report = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eception_top_three_sales = new javax.swing.JButton();
        exception_top_three_income = new javax.swing.JButton();
        today_date_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date_today = new datechooser.beans.DateChooserCombo();
        end_date_combo = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout graph_destinationLayout = new javax.swing.GroupLayout(graph_destination);
        graph_destination.setLayout(graph_destinationLayout);
        graph_destinationLayout.setHorizontalGroup(
            graph_destinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        graph_destinationLayout.setVerticalGroup(
            graph_destinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout report_panelLayout = new javax.swing.GroupLayout(report_panel);
        report_panel.setLayout(report_panelLayout);
        report_panelLayout.setHorizontalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(html_other_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(report_panelLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(graph_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        report_panelLayout.setVerticalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panelLayout.createSequentialGroup()
                .addComponent(html_other_label, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(graph_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        detail_report.setText("Detail report");
        detail_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_reportActionPerformed(evt);
            }
        });

        exception_top_sales.setText("Eception Report - Top sales report");
        exception_top_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exception_top_salesActionPerformed(evt);
            }
        });

        back_to_menu.setText("Back to menu");
        back_to_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_menuActionPerformed(evt);
            }
        });

        summary_report.setText("Summary Report");
        summary_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summary_reportActionPerformed(evt);
            }
        });

        eception_top_three_sales.setText("Exception Report - Top 3 sold product");
        eception_top_three_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eception_top_three_salesActionPerformed(evt);
            }
        });

        exception_top_three_income.setText("Exception Report - Top 3 income product");
        exception_top_three_income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exception_top_three_incomeActionPerformed(evt);
            }
        });

        today_date_label.setText("Today Date : ");

        jLabel4.setText(" Select start date and end date : ");

        jLabel5.setText(" Start Date : ");

        jLabel6.setText(" End Date : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detail_report, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exception_top_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summary_report, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_to_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eception_top_three_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exception_top_three_income, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end_date_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_today, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(today_date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(today_date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detail_report, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exception_top_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eception_top_three_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exception_top_three_income, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summary_report, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back_to_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(date_today, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(end_date_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        detail_report.getAccessibleContext().setAccessibleName("");
        exception_top_sales.getAccessibleContext().setAccessibleName("");
        back_to_menu.getAccessibleContext().setAccessibleName("");
        summary_report.getAccessibleContext().setAccessibleName("");
        eception_top_three_sales.getAccessibleContext().setAccessibleName("");
        exception_top_three_income.getAccessibleContext().setAccessibleName("");
        date_today.getAccessibleContext().setAccessibleName("");
        end_date_combo.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void summary_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summary_reportActionPerformed
        // TODO add your handling code here:
        this.jScrollPane1.setViewportView(this.report_panel);
        set_start_end();
        Report_SummaryReport run = new Report_SummaryReport(this.start_date, this.end_date);
        run.generateSummaryReport();
        run.write_full_report();
        this.html_other_label.setText(run.getReport());
        this.graph_destination.removeAll();
        this.graph_destination.add(run.write_chart());
        this.graph_destination.updateUI();
    }//GEN-LAST:event_summary_reportActionPerformed

    private StyleSheet report_css(){
        StyleSheet css = new StyleSheet();
        try {
            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream("resource/html/css/report.css")));
            css.loadRules(br, null);
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interface_Report.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interface_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
        return css;
    }
    
    private void detail_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_reportActionPerformed
        // TODO add your handling code here:
        Report_DetailReport run = new Report_DetailReport(this.date_today.getSelectedDate().getTime(), this.end_date_combo.getSelectedDate().getTime());
        run.write_full_report();
        this.jScrollPane1.setViewportView(this.label_html);
        label_html.setText(run.getReport());
    }//GEN-LAST:event_detail_reportActionPerformed

    private void exception_top_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exception_top_salesActionPerformed
        set_start_end();
        Report_ExceptionReport run = new Report_ExceptionReport(this.start_date, this.end_date);
        run.generate_exception_report(10, "sum_of_product");
        run.write_full_report();
        this.jScrollPane1.setViewportView(this.label_html);
        label_html.setText(run.getReport());
    }//GEN-LAST:event_exception_top_salesActionPerformed

    private void eception_top_three_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eception_top_three_salesActionPerformed
        // TODO add your handling code here:
        this.jScrollPane1.setViewportView(this.report_panel);
        set_start_end();
        Report_Top_3_Sold run = new Report_Top_3_Sold(this.start_date, this.end_date);
        run.generate_exception_report();
        run.write_full_report();
        this.html_other_label.setText(run.getReport());
        this.graph_destination.removeAll();
        this.graph_destination.add(run.write_chart());
        this.graph_destination.updateUI();
    }//GEN-LAST:event_eception_top_three_salesActionPerformed

    private void exception_top_three_incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exception_top_three_incomeActionPerformed
        // TODO add your handling code here:
        this.jScrollPane1.setViewportView(this.report_panel);
        set_start_end();
        Report_Top_3_outcome run = new Report_Top_3_outcome(this.start_date, this.end_date);
        run.generate_exception_report();
        run.write_full_report();
        this.html_other_label.setText(run.getReport());
        this.graph_destination.removeAll();
        this.graph_destination.add(run.write_chart());
        this.graph_destination.updateUI();
    }//GEN-LAST:event_exception_top_three_incomeActionPerformed

    private void back_to_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_menuActionPerformed
        // TODO add your handling code here:
        new Interface_MenuManager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_to_menuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_menu;
    private datechooser.beans.DateChooserCombo date_today;
    private javax.swing.JButton detail_report;
    private javax.swing.JButton eception_top_three_sales;
    private datechooser.beans.DateChooserCombo end_date_combo;
    private javax.swing.JButton exception_top_sales;
    private javax.swing.JButton exception_top_three_income;
    private javax.swing.JPanel graph_destination;
    private javax.swing.JLabel html_other_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_html;
    private javax.swing.JPanel report_panel;
    private javax.swing.JButton summary_report;
    private javax.swing.JLabel today_date_label;
    // End of variables declaration//GEN-END:variables
}
