package Interface;


import User.Staff.Department;
import Main.Main;
import Transaction.Payment;
import User.Staff.Staff;
import User.Staff.StaffLevel;
import SubInterface.SubInterface_Login_Staff;
import Sql.WriteSql;


import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ITSUKA KOTORI
 */
public class Interface_Staff_manager extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Staff_manager
     */
    
    private String inputException = "";
    private JTable staffTable;
    private final String[] columns;
    private  String[] rows = new String[8];
    private boolean input_validate;
    private DefaultTableModel model = new DefaultTableModel();
    private Staff loginedStaff;
    private ButtonGroup input_gender_group = new ButtonGroup();
    
    
    public final String getDataDutyStaff(){
        File temp_f = new File("resource/data/staff_id_logedin.txt");
        if (temp_f.isFile()) {
            try {
                BufferedReader br = new BufferedReader(new FileReader(temp_f));
                try {
                    return br.readLine();
                } catch (IOException ex) {
                    Logger.getLogger(Interface_MenuManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }catch (FileNotFoundException ex) {
                Logger.getLogger(Interface_MenuManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return "";
    }
    
    public Interface_Staff_manager() {
        this.columns = new String[]{"Staff ID", "Staff Name", "Phone number", "Join Date", "Gender", "Position", "Address"};
        this.loginedStaff = new Staff(SubInterface_Login_Staff.decode_id(this.getDataDutyStaff()));
        initComponents();
        initComponents_Interface();
        initComponents_Table();
        initComponents_data();
        initComponents_SetClose();
        initComponents_date_time();
        this.bSearch_id_btn.setEnabled(true);
        this.total_staff.setText("Total Staff Found : " + this.staffTable.getRowCount());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_pane = new javax.swing.JScrollPane();
        submit_pane = new javax.swing.JPanel();
        bCommit_add_btn = new javax.swing.JButton();
        bAdd_new_btn = new javax.swing.JButton();
        bModify_btn = new javax.swing.JButton();
        bCommit_modify_btn = new javax.swing.JButton();
        bRefresh_btn = new javax.swing.JButton();
        bBack_menu_btn = new javax.swing.JButton();
        bDelete_btn = new javax.swing.JButton();
        label_time = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        staff_status_pane = new javax.swing.JPanel();
        bSearch_id_btn = new javax.swing.JButton();
        empty_pane = new javax.swing.JPanel();
        input_staff_id = new javax.swing.JTextField();
        label_staff_id = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        input_address = new javax.swing.JTextArea();
        label_address = new javax.swing.JLabel();
        label_working_hours = new javax.swing.JLabel();
        label_salary = new javax.swing.JLabel();
        label_salary_rate_hours = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        input_email = new javax.swing.JTextField();
        input_salary_rate = new javax.swing.JPasswordField();
        input_salary = new javax.swing.JPasswordField();
        input_working_hours = new javax.swing.JTextField();
        input_department = new javax.swing.JComboBox<>();
        label_department = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        input_male_gender = new javax.swing.JRadioButton();
        input_new_password = new javax.swing.JPasswordField();
        input_password = new javax.swing.JPasswordField();
        input_female_gender = new javax.swing.JRadioButton();
        input_Staff_position = new javax.swing.JComboBox<>();
        input_fName = new javax.swing.JTextField();
        input_lName = new javax.swing.JTextField();
        input_phone = new javax.swing.JTextField();
        label_gender = new javax.swing.JLabel();
        label_lName = new javax.swing.JLabel();
        label_new_password = new javax.swing.JLabel();
        label_old_password = new javax.swing.JLabel();
        label_staff_position = new javax.swing.JLabel();
        input_other_gender = new javax.swing.JRadioButton();
        label_join_date = new javax.swing.JLabel();
        label_fName = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_staff_ic = new javax.swing.JLabel();
        input_staff_ic = new javax.swing.JTextField();
        input_joindate = new datechooser.beans.DateChooserCombo();
        total_staff = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff manager");

        bCommit_add_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bCommit_add_btn.setText("Commit Add");
        bCommit_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCommit_add_btnActionPerformed(evt);
            }
        });

        bAdd_new_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bAdd_new_btn.setText("Add New");
        bAdd_new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdd_new_btnActionPerformed(evt);
            }
        });

        bModify_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bModify_btn.setText("Modify");
        bModify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModify_btnActionPerformed(evt);
            }
        });

        bCommit_modify_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bCommit_modify_btn.setText("Commit Modify");
        bCommit_modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCommit_modify_btnActionPerformed(evt);
            }
        });

        bRefresh_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bRefresh_btn.setText("Refresh");
        bRefresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefresh_btnActionPerformed(evt);
            }
        });

        bBack_menu_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bBack_menu_btn.setText("Back To Menu");
        bBack_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBack_menu_btnActionPerformed(evt);
            }
        });

        bDelete_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bDelete_btn.setText("Delete");
        bDelete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelete_btnActionPerformed(evt);
            }
        });

        label_time.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_time.setText("Time : ");

        label_date.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_date.setText("Date : ");

        javax.swing.GroupLayout submit_paneLayout = new javax.swing.GroupLayout(submit_pane);
        submit_pane.setLayout(submit_paneLayout);
        submit_paneLayout.setHorizontalGroup(
            submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submit_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDelete_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submit_paneLayout.createSequentialGroup()
                        .addComponent(bRefresh_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBack_menu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addComponent(label_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(submit_paneLayout.createSequentialGroup()
                        .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bModify_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAdd_new_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCommit_add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(bCommit_modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(submit_paneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        submit_paneLayout.setVerticalGroup(
            submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submit_paneLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(label_time, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCommit_add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd_new_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCommit_modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bModify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bDelete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBack_menu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(submit_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(submit_paneLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(label_date, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );

        bSearch_id_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bSearch_id_btn.setText("Search");
        bSearch_id_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearch_id_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout empty_paneLayout = new javax.swing.GroupLayout(empty_pane);
        empty_pane.setLayout(empty_paneLayout);
        empty_paneLayout.setHorizontalGroup(
            empty_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        empty_paneLayout.setVerticalGroup(
            empty_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        input_staff_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_staff_idKeyTyped(evt);
            }
        });

        label_staff_id.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_staff_id.setText("Staff ID");

        input_address.setColumns(20);
        input_address.setRows(5);
        jScrollPane2.setViewportView(input_address);

        label_address.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_address.setText("Address");

        label_working_hours.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_working_hours.setText("Working Hours");

        label_salary.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_salary.setText("Salary");

        label_salary_rate_hours.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_salary_rate_hours.setText("Salary Rate per Hours");

        label_email.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_email.setText("Email Address");

        input_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_salaryActionPerformed(evt);
            }
        });

        input_department.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        input_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        input_department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                input_departmentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_departmentMousePressed(evt);
            }
        });
        input_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_departmentActionPerformed(evt);
            }
        });

        label_department.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_department.setText("Department");

        javax.swing.GroupLayout staff_status_paneLayout = new javax.swing.GroupLayout(staff_status_pane);
        staff_status_pane.setLayout(staff_status_paneLayout);
        staff_status_paneLayout.setHorizontalGroup(
            staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staff_status_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addComponent(label_staff_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addComponent(label_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addComponent(label_salary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addComponent(label_salary_rate_hours, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_salary_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staff_status_paneLayout.createSequentialGroup()
                        .addComponent(label_working_hours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_working_hours, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addComponent(label_department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_department, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empty_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSearch_id_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        staff_status_paneLayout.setVerticalGroup(
            staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_status_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_staff_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_working_hours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_working_hours, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_salary_rate_hours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_salary_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_department)
                            .addComponent(label_department, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staff_status_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_address, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(staff_status_paneLayout.createSequentialGroup()
                        .addComponent(bSearch_id_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(empty_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );

        jPanel1.setMinimumSize(new java.awt.Dimension(477, 403));

        input_male_gender.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        input_male_gender.setText("Male");

        input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_passwordActionPerformed(evt);
            }
        });

        input_female_gender.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        input_female_gender.setText("Female");

        input_Staff_position.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        input_Staff_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        input_Staff_position.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                input_Staff_positionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_Staff_positionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                input_Staff_positionMouseReleased(evt);
            }
        });
        input_Staff_position.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_Staff_positionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_Staff_positionKeyReleased(evt);
            }
        });

        input_fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_fNameActionPerformed(evt);
            }
        });

        input_lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_lNameActionPerformed(evt);
            }
        });

        label_gender.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_gender.setText("Gender");

        label_lName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_lName.setText("Last Name");

        label_new_password.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_new_password.setText("New password");

        label_old_password.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_old_password.setText("Old password");

        label_staff_position.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_staff_position.setText("Staff Position");

        input_other_gender.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        input_other_gender.setText("Other");
        input_other_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_other_genderActionPerformed(evt);
            }
        });

        label_join_date.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_join_date.setText("Join date");

        label_fName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_fName.setText("First Name");

        label_phone.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_phone.setText("Phone number");

        label_staff_ic.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_staff_ic.setText("Staff IC");

        input_joindate.setFieldFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12));

        total_staff.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        total_staff.setText("Total Staff Found : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(input_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(input_lName))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_old_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_new_password, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_join_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_joindate, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_male_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_female_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_other_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_staff_position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_Staff_position, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(label_staff_ic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_staff_ic, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(total_staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(label_fName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_lName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_staff_ic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_staff_ic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_old_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_new_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_join_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_joindate, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_male_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_female_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_other_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_Staff_position)
                    .addComponent(label_staff_position, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(data_pane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staff_status_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submit_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, Short.MAX_VALUE))
                    .addComponent(staff_status_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submit_pane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_fNameActionPerformed

    private void input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passwordActionPerformed

    private void input_other_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_other_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_other_genderActionPerformed

    private void bModify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModify_btnActionPerformed

        Staff temp = new Staff(model.getValueAt(staffTable.getSelectedRow(), 0).toString());
        if(this.loginedStaff.getLevel().position() > temp.getLevel().position()){ 
            this.partButton(false);
            this.bCommit_modify_btn.setEnabled(true);
            this.change_refresh_buttonTo_cancle(true);
            this.input_staff_ic.setText(temp.getUser_ic());
            this.openInput(temp);
        }else{
            JOptionPane.showConfirmDialog(null, "Your position is lower than or equal the selected staff, you unable to modify the employee higher position than you!!", "Modify Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bModify_btnActionPerformed

    private void bCommit_modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCommit_modify_btnActionPerformed
        int i = staffTable.getSelectedRow();
        Staff temp = new Staff(input_staff_id.getText());
        Staff data = this.get_input();
        if (data != null) {
                if (this.loginedStaff.getLevel().position() > temp.getLevel().position()) {                    
                    if (JOptionPane.showConfirmDialog(null, "Do you sure want to up at the following staff " + temp.getUser_id() + " information", "Confrim Modify", 0) == 0) {
                        this.partButton(true);
                        this.bCommit_modify_btn.setEnabled(false);
                        this.change_refresh_buttonTo_cancle(false);
                        model.setValueAt(data.getUser_id(), i, 0);
                        model.setValueAt(data.getFullName(), i, 1);
                        model.setValueAt(data.getPhoneNumber(), i, 2);
                        model.setValueAt(WriteSql.DATE_FORMAT.format(data.getJoin_date()), i, 3);
                        model.setValueAt(data.getGender().toString(), i, 4);
                        model.setValueAt(data.getLevel().toString(), i, 5);
                        model.setValueAt(data.getAddress(), i, 6);
                        this.set_input();
                        this.closeInput();
                        data.modify_this();
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "Your position is lower than the selected staff, you unable to modify the employee higher position than you!!", "Modify Error", JOptionPane.WARNING_MESSAGE);
                    this.partButton(true);
                    this.bCommit_modify_btn.setEnabled(false);
                    this.change_refresh_buttonTo_cancle(false);
                    this.closeInput();
                }
        } else {
            JOptionPane.showConfirmDialog(null, "Invalid input data is found as following in your input, Please enter the correct data.\n" + inputException, "Invalid input data", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bCommit_modify_btnActionPerformed

    private void bAdd_new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdd_new_btnActionPerformed
        this.partButton(false);
        this.set_input();
        this.bCommit_add_btn.setEnabled(true);
        this.change_refresh_buttonTo_cancle(true);
        this.openInput_add_new(SubInterface_Login_Staff.decode_id(getDataDutyStaff()));
        this.input_staff_id.setText(new Staff(SubInterface_Login_Staff.decode_id(getDataDutyStaff())).generate_id("Other").substring(2, 6));
        this.staffTable.clearSelection();
    }//GEN-LAST:event_bAdd_new_btnActionPerformed

    private Staff get_input(){
        boolean test = true;
        Staff data = new Staff( "0", "0", "0", 
                (String)this.input_Staff_position.getSelectedItem(), (String)this.input_department.getSelectedItem(), this.input_staff_id.getText(),
                "", "", "", "", 
                this.input_male_gender.isSelected()?"M":"F", "", WriteSql.DATE_FORMAT.format(this.input_joindate.getSelectedDate().getTime()), 
                "", "");
        if(!data.setSalary(this.input_salary.getText())){
            inputException += "Invalid salary the salary must be in range of RM 00.0 to RM 150000.00  !!\n";
            test &= false;
        }if(!data.setSalary_rate_hours(input_salary_rate.getText())){
            inputException += "Invalid salary/hours the salary must be in range of RM 00.0 to RM 150.00 !!\n";
            test &= false;
        }if(!data.setWorkingHour(this.input_working_hours.getText())){
            inputException += "Invalid working hours the time of working hour max is 16 !!\n";
            test &= false;
        }
        if (!"".equals(this.input_password.getText()) || this.input_password.getText() != null) {
            String password = data.getLogin_password();
            if (data.setFristPassword(this.input_password.getText(), this.input_new_password.getText()) == false) {
                inputException += "Invalid Password the password at least need 8 word and must be a-z/A-Z/0-9 !!\n";
                test &= false;
            }
        }
        if(!data.setPhoneNumber(this.input_phone.getText())){
            inputException += "Invalid phonenumber please check back the format 019-9999999 !!\n";
            test &= false;
        }if(!data.setFName(this.input_fName.getText())){
            inputException += "Invalid frist name, the name only valid in a-z or A-Z !!\n";
            test &= false;
        }if(!data.setLName(this.input_lName.getText())){
            inputException += "Invalid last name, the name only valid in a-z or A-Z !!\n";
            test &= false;
        }if(!data.setAddress(this.input_address.getText())){
            inputException += "Invalid home address the home address cannot contain ',' !!\n";
            test &= false;
        }if(!data.setEmail(this.input_email.getText())){
            inputException += "Invalid email address please check back you email address !!\n";
            test &= false;
        }if(!data.setUser_ic(this.input_staff_ic.getText())){
            inputException += "Invalid IC number please check back the format is 999999-99-9999 !!\n";
            test &= false;
        }
        if (test) {
            return data;
        } else {
            return null;
        }
    }
    private void bCommit_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCommit_add_btnActionPerformed
        Staff data = get_input();
        if (data != null && !("".equals(this.input_password.getText()) ||this.input_password.getText() == null)) {
            data.setUser_id(data.generate_id(data.getLevel().id_database()));
            if (data.isNotNull()) {
                if (new Staff(SubInterface_Login_Staff.decode_id(getDataDutyStaff())).isManager() == true) {
                    if (WriteSql.getUniqueInt("SELECT COUNT(staff_id) FROM Staff WHERE email_address='" + this.input_email.getText() + "';") == 0) {
                        
                        if (JOptionPane.showConfirmDialog(null, "Do you sure want to add the folowing person " + data.getFullName() + " as a new staff position at " + data.getLevel() + " id " + data.getDepartment() + " department", "Confirm Add", 0) == 0) {
                            this.set_input();
                            this.input_staff_id.setText(new Staff(SubInterface_Login_Staff.decode_id(getDataDutyStaff())).generate_id(this.input_Staff_position.getSelectedItem().toString()));                            
                            this.partButton(true);
                            System.out.println(data.toString());
                            if (data.write_this()) {
                                System.out.println("Successful");
                            } else {
                                System.out.println("Fail to access");
                            }
                            this.write_table_row(data);
                            this.bCommit_add_btn.setEnabled(false);
                            this.change_refresh_buttonTo_cancle(false);
                            this.closeInput();
                            this.set_input();
                            this.total_staff.setText("Total Product Found : " + this.staffTable.getRowCount());
                        }
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "Only manager can add new staff, you are not allow to add nes=w staff", "Position not enough", JOptionPane.CLOSED_OPTION);
                }
            } else {
                JOptionPane.showConfirmDialog(null, "Invalid input data found", "Adding error", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Invalid input data is found as following in your input, Please enter the correct data.\n" + inputException, "Invalid input data", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bCommit_add_btnActionPerformed

    private void bDelete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelete_btnActionPerformed
        
        Staff temp;
        if(staffTable.getSelectedRow() >= 0)
            temp = new Staff(model.getValueAt(staffTable.getSelectedRow(), 0).toString());
        else
            temp = new Staff(this.input_staff_id.getText());
        
        if(this.loginedStaff.getLevel().position() > temp.getLevel().position()){ 
            if(staffTable.getSelectedRow() >= 0){
                if (JOptionPane.showConfirmDialog(null, "Do you sure want to delete the following staff " + temp.getUser_id() , "Confirm delete", 0) == 0) {
                    model.removeRow(staffTable.getSelectedRow());
                    if (temp.delete_this()) {
                        System.out.println("The staff is successful deleted by user : " + SubInterface_Login_Staff.decode_id(this.getDataDutyStaff()));
                    } else {
                        System.out.println("The file is cannot access by the system, please check back the data");
                    }
                    this.staffTable.clearSelection();
                }
            }else{
                boolean found = false;
                for(int i = 0;i < staffTable.getRowCount(); i++){
                    if(model.getValueAt(i,0).equals(temp.getUser_id())){
                        if (JOptionPane.showConfirmDialog(null, "Do you sure want to delete the following staff " + temp.getUser_id(), "Confrim delete", 0) == 0) {
                            found = true;
                            staffTable.remove(i);
                            temp.delete_this();
                            set_input();
                        }
                    }
                }
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Your position is lower than the selected staff, you unable to delete the employee higher position than you!!", "Delete Error", JOptionPane.WARNING_MESSAGE);
        }
        this.total_staff.setText("Total Staff Found : " + this.staffTable.getRowCount());
    }//GEN-LAST:event_bDelete_btnActionPerformed

    private void bRefresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefresh_btnActionPerformed
        this.set_input();
        if(this.bRefresh_btn.getText().equals("Cancel")){
            this.partButton(true);
            this.change_refresh_buttonTo_cancle(false);
        }
        else{
            while(this.model.getRowCount() > 0){
                this.model.removeRow(0);
            }
            this.initComponents_data();
            //need to add refreash 
        }
        this.total_staff.setText("Total Staff Found : " + this.staffTable.getRowCount());
    }//GEN-LAST:event_bRefresh_btnActionPerformed

    private void bSearch_id_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearch_id_btnActionPerformed
        if(this.bSearch_id_btn.getText().equals("Search")){
            this.bSearch_id_btn.setText("Find");
            this.input_staff_id.setEditable(true);
        }else if(this.bSearch_id_btn.getText().equals("Find")){
            this.bSearch_id_btn.setText("Search");
            this.input_staff_id.setEditable(false);
            if(WriteSql.getUniqueInt("SELECT COUNT(*) FROM STAFF WHERE staff_id='" + input_staff_id.getText() +  "';") == 1){
                this.set_input(input_staff_id.getText());
            }else{
                this.set_input();
                input_staff_id.setText("No record found");
            }
        }
        this.staffTable.clearSelection();
    }//GEN-LAST:event_bSearch_id_btnActionPerformed

    private void input_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_salaryActionPerformed

    private void input_Staff_positionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_Staff_positionKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_input_Staff_positionKeyReleased

    private void input_Staff_positionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_Staff_positionMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_input_Staff_positionMouseReleased

    private void input_departmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_departmentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_departmentMousePressed

    private void input_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_departmentActionPerformed

    private void input_departmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_departmentMouseExited
        // TODO add your handling code here
    }//GEN-LAST:event_input_departmentMouseExited

    private void input_Staff_positionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_Staff_positionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_input_Staff_positionMouseExited

    private void input_Staff_positionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_Staff_positionMousePressed
        // TODO add your handling code here
    }//GEN-LAST:event_input_Staff_positionMousePressed

    private void input_Staff_positionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_Staff_positionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_Staff_positionKeyPressed

    private void bBack_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBack_menu_btnActionPerformed
        new Interface_MenuManager().setVisible(true);
        dispose();
    }//GEN-LAST:event_bBack_menu_btnActionPerformed

    private void input_staff_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_staff_idKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_input_staff_idKeyTyped

    private void input_lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_lNameActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd_new_btn;
    private javax.swing.JButton bBack_menu_btn;
    private javax.swing.JButton bCommit_add_btn;
    private javax.swing.JButton bCommit_modify_btn;
    private javax.swing.JButton bDelete_btn;
    private javax.swing.JButton bModify_btn;
    private javax.swing.JButton bRefresh_btn;
    private javax.swing.JButton bSearch_id_btn;
    private javax.swing.JScrollPane data_pane;
    private javax.swing.JPanel empty_pane;
    private javax.swing.JComboBox<String> input_Staff_position;
    private javax.swing.JTextArea input_address;
    private javax.swing.JComboBox<String> input_department;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_fName;
    private javax.swing.JRadioButton input_female_gender;
    private datechooser.beans.DateChooserCombo input_joindate;
    private javax.swing.JTextField input_lName;
    private javax.swing.JRadioButton input_male_gender;
    private javax.swing.JPasswordField input_new_password;
    private javax.swing.JRadioButton input_other_gender;
    private javax.swing.JPasswordField input_password;
    private javax.swing.JTextField input_phone;
    private javax.swing.JPasswordField input_salary;
    private javax.swing.JPasswordField input_salary_rate;
    private javax.swing.JTextField input_staff_ic;
    private javax.swing.JTextField input_staff_id;
    private javax.swing.JTextField input_working_hours;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_department;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_fName;
    private javax.swing.JLabel label_gender;
    private javax.swing.JLabel label_join_date;
    private javax.swing.JLabel label_lName;
    private javax.swing.JLabel label_new_password;
    private javax.swing.JLabel label_old_password;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_salary;
    private javax.swing.JLabel label_salary_rate_hours;
    private javax.swing.JLabel label_staff_ic;
    private javax.swing.JLabel label_staff_id;
    private javax.swing.JLabel label_staff_position;
    private javax.swing.JLabel label_time;
    private javax.swing.JLabel label_working_hours;
    private javax.swing.JPanel staff_status_pane;
    private javax.swing.JPanel submit_pane;
    private javax.swing.JLabel total_staff;
    // End of variables declaration//GEN-END:variables

    private void initComponents_Interface() {
        this.setIconImage(Main.DEFUALT_ICON.getImage());
        this.partButton(false);
        this.bAdd_new_btn.setEnabled(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.input_Staff_position.setModel(new DefaultComboBoxModel<>(new String[] {
            StaffLevel.ACCOUNTANT.toString(),StaffLevel.CASHEIR.toString(),StaffLevel.DECESION_MANAGER.toString(),StaffLevel.DEPARTMENT_MANAGER.toString(),StaffLevel.MANAGER.toString(),StaffLevel.PORTER.toString(),StaffLevel.PROMOTER.toString(),StaffLevel.OTHER_STAFF.toString() 
        }));
        this.input_department.setModel(new DefaultComboBoxModel<>(new String[] {
            Department.myValueOf("D001").toString(),
            Department.myValueOf("D002").toString(),
            Department.myValueOf("D003").toString(),
            Department.myValueOf("D004").toString(),
            Department.myValueOf("D005").toString(),
            Department.myValueOf("D006").toString(),
            Department.myValueOf("D007").toString(),
            Department.myValueOf("D008").toString(),
            Department.myValueOf("D009").toString()
        }));
        this.closeInput();
        input_gender_group.add(this.input_female_gender);
        input_gender_group.add(this.input_male_gender);
        input_gender_group.add(this.input_other_gender);
    }

    private void initComponents_Table() {
        staffTable = new JTable(){ @Override public boolean isCellEditable(int rowIndex, int colIndex){ return false; /* disable edit */}};
        this.data_pane.add(staffTable);
        model = new DefaultTableModel(0,7);
        model.setColumnIdentifiers(columns);
        staffTable.setModel(model);
        staffTable.setBackground(Color.white);
        staffTable.setForeground(Color.DARK_GRAY);
        data_pane.setViewportView(staffTable);

        Font font = new Font("", 0, 12);
        staffTable.setFont(font);
        staffTable.setRowHeight(20);
        staffTable.getColumnModel().getColumn(0).setPreferredWidth(70);
        staffTable.getColumnModel().getColumn(1).setPreferredWidth(140);
        staffTable.getColumnModel().getColumn(2).setPreferredWidth(120);
        staffTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        staffTable.getColumnModel().getColumn(4).setPreferredWidth(90);
        staffTable.getColumnModel().getColumn(5).setPreferredWidth(160);
        staffTable.getColumnModel().getColumn(6).setPreferredWidth(580);
        
        staffTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                    productTableactive();
            }
        });
        
                
        staffTable.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
                    productTableactive();
                }
            }
        });
    }

    private void initComponents_data() {
      Staff temp = new Staff();
      try
        {            
            try (Connection conn = DriverManager.getConnection("jdbc:ucanaccess://resource/data/Point_of_sales.mdb;"); Statement s = conn.createStatement()) {
                s.execute("SELECT * FROM STAFF ORDER BY SUBSTRING(STAFF_ID,3,8);");
                ResultSet result = s.getResultSet();
                while(result.next()){
                    temp.split(result);
                    this.write_table_row(temp);
                }
                result.close();
                s.close();
                conn.close();
            }
        }
        catch(SQLException ex){
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initComponents_date_time() {
        Date today = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat timeformat = new SimpleDateFormat("hh:mm:ss");
        label_time.setText("Date: " + format.format(today));
        this.label_date.setText("Time: " + timeformat.format(today));
    }

    private void initComponents_SetClose() {
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                bBack_menu_btnActionPerformed(null);
            }
        });
    }
    
    private void closeInput(){
        this.input_Staff_position.setEditable(false);
        this.input_Staff_position.setEnabled(false);
        this.input_address.setEditable(false);
        this.input_fName.setEditable(false);
        this.input_female_gender.setEnabled(false);
        this.input_male_gender.setEnabled(false);
        this.input_other_gender.setEnabled(false);
        this.input_joindate.setEnabled(false);
        this.input_lName.setEditable(false);
        this.input_password.setEditable(false);
        this.input_phone.setEditable(false);
        this.input_new_password.setEditable(false);
        this.input_staff_id.setEditable(false);
        this.input_staff_ic.setEditable(false);
        this.input_working_hours.setEditable(false);
        this.input_salary.setEditable(false);
        this.input_salary_rate.setEditable(false);
        this.input_email.setEditable(false);
        this.input_department.setEditable(false);
        this.input_salary.setVerifyInputWhenFocusTarget(false);
        this.input_salary_rate.setVerifyInputWhenFocusTarget(false);
    }
    
    private void openInput(Staff selected_staff){
        if(this.loginedStaff.getLevel().level_number() > selected_staff.getLevel().position() || this.loginedStaff.getLevel().position() == 4){
            this.input_Staff_position.setEditable(true);
            this.input_Staff_position.setEnabled(true);
            this.input_joindate.setEnabled(true);
            this.input_address.setEditable(true);
            this.input_fName.setEditable(true);
            this.input_female_gender.setEnabled(true);
            this.input_male_gender.setEnabled(true);
            this.input_other_gender.setEnabled(true);
            this.input_lName.setEditable(true);
            this.input_phone.setEditable(true);
            this.input_password.setEditable(true);
            this.input_new_password.setEditable(true);
            this.input_staff_id.setEditable(false);
            this.input_staff_ic.setEditable(true);
            this.input_working_hours.setEditable(true);
            this.input_salary.setEditable(true);
            this.input_salary.setVerifyInputWhenFocusTarget(true);
            this.input_salary_rate.setEditable(true);
            this.input_email.setEditable(true);
            this.input_department.setEditable(true);
        this.input_salary_rate.setVerifyInputWhenFocusTarget(true);
        }
        else if (selected_staff.getUser_id() == null ? loginedStaff.getUser_id() == null : selected_staff.getUser_id().equals(loginedStaff.getUser_id())){
            this.input_address.setEditable(true);
            this.input_phone.setEditable(true);
            this.input_password.setEditable(true);
            this.input_new_password.setEditable(true);
            this.input_email.setEditable(true);
            this.input_salary.setVerifyInputWhenFocusTarget(true);
            this.input_salary_rate.setVerifyInputWhenFocusTarget(true);
        }
        else{
            JOptionPane.showConfirmDialog(null, "Your position is lower than the selected staff, you unable to edit all the employee higher position than you!!", "", JOptionPane.DEFAULT_OPTION);
        }
    }
    
    private void openInput_add_new(String selected_staff_id){
        if(new Staff(selected_staff_id).getLevel().level_number() > 0){
            this.input_Staff_position.setEditable(true);
            this.input_Staff_position.setEnabled(true);
            this.input_joindate.setEnabled(true);
            this.input_address.setEditable(true);
            this.input_fName.setEditable(true);
            this.input_female_gender.setEnabled(true);
            this.input_male_gender.setEnabled(true);
            this.input_other_gender.setEnabled(true);
            this.input_lName.setEditable(true);
            this.input_phone.setEditable(true);
            this.input_password.setEditable(true);
            this.input_new_password.setEditable(true);
            this.input_staff_id.setEditable(false);
            this.input_staff_ic.setEditable(true);
            this.input_working_hours.setEditable(true);
            this.input_salary.setEditable(true);
            this.input_salary_rate.setEditable(true);
            this.input_email.setEditable(true);
            this.input_department.setEditable(true);
            this.input_salary.setVerifyInputWhenFocusTarget(false);
            this.input_salary_rate.setVerifyInputWhenFocusTarget(false);
        }
        else{
            System.out.println("You are not able to add a new staff");
            JOptionPane.showConfirmDialog(null, "You are not able to add a new staff", "Error Message", JOptionPane.DEFAULT_OPTION);
        }
    }
    
    private void partButton(boolean status){
        this.bAdd_new_btn.setEnabled(status);
        this.bBack_menu_btn.setEnabled(true);// if exit force stop all process and will not save
        this.bCommit_add_btn.setEnabled(false);
        this.bCommit_modify_btn.setEnabled(false);
        this.bDelete_btn.setEnabled(false);
        this.bModify_btn.setEnabled(false);
        this.bRefresh_btn.setEnabled(true);// force refresh all will stop
        this.bSearch_id_btn.setEnabled(status);
    }
    
    private void allButton(boolean status){
        this.bAdd_new_btn.setEnabled(status);
        this.bBack_menu_btn.setEnabled(true);// if exit force stop all process and will not save
        this.bCommit_add_btn.setEnabled(false);
        this.bCommit_modify_btn.setEnabled(false);
        this.bDelete_btn.setEnabled(status);
        this.bModify_btn.setEnabled(status);
        this.bRefresh_btn.setEnabled(true);// force refresh all will stop
        this.bSearch_id_btn.setEnabled(status);
    }
        
    private void productTableactive(){
        allButton(true);
        int i = this.staffTable.getSelectedRow();
        this.set_input(model.getValueAt(i, 0).toString());
        this.closeInput();
    }

    private void write_table_row(Staff temp) {
        String[] data = new String[7];
        data[0] = temp.getUser_id();
        data[1] = temp.getFullName();
        data[2] = temp.getPhoneNumber();
        data[3] = WriteSql.DATE_FORMAT.format(temp.getJoin_date());
        data[4] = temp.getGender().toString();
        data[5] = temp.getLevel().toString();
        data[6] = temp.getAddress();
        this.model.addRow(data);
    }
    
    private void change_refresh_buttonTo_cancle(boolean status_X){
        if(status_X){
            this.bRefresh_btn.setEnabled(true);
            this.bRefresh_btn.setText("Cancel");
        }
        else{
            this.bRefresh_btn.setText("Refresh");
        }
        closeInput();
    }

    private void set_input() {
        this.input_Staff_position.setSelectedIndex(7);
        this.input_address.setText("");
        this.input_fName.setText("");
        this.input_female_gender.setSelected(false);
        this.input_male_gender.setSelected(false);
        this.input_other_gender.setSelected(false);
        this.input_joindate.setText("Date : " + WriteSql.DATE_FORMAT.format(Main.getToday_date()));
        this.input_lName.setText("");
        this.input_password.setText("");
        this.input_phone.setText("");
        this.input_new_password.setText("");
        this.input_staff_id.setText("");
        this.input_staff_ic.setText("");
        this.input_department.setSelectedIndex(8);
        this.input_email.setText("");
        this.input_salary.setText("");
        this.input_salary_rate.setText("");
        this.input_working_hours.setText("");
    }
    private void set_input(String staff_id) {
        Staff staff = new Staff(staff_id);
        this.input_Staff_position.setSelectedIndex(staff.getLevel().level_number());
        this.input_address.setText(staff.getAddress());
        this.input_fName.setText(staff.getfName());
        this.input_joindate.setText("Date : " + WriteSql.DATE_FORMAT.format(staff.getJoin_date()));
        this.input_lName.setText(staff.getlName());
        this.input_password.setText("");
        this.input_phone.setText(staff.getPhoneNumber());
        this.input_new_password.setText("");
        this.input_staff_id.setText(staff.getUser_id());
        this.input_staff_ic.setText(staff.getUser_ic());
        this.input_department.setSelectedIndex(staff.getDepartment().toIndex());
        this.input_email.setText(staff.getEmail());
        this.input_salary.setText(String.format("%.2f", staff.getSalary()));
        this.input_salary_rate.setText(String.format("%.2f", staff.getSalary_rate_hours()));
        this.input_working_hours.setText(staff.getWorkingHours() + "");
        this.input_female_gender.setSelected(false);
        this.input_male_gender.setSelected(false);
        this.input_other_gender.setSelected(false);
        if(null == staff.getGender()){
            this.input_other_gender.setSelected(true);
        }
        else switch (staff.getGender()) {
            case FEMALE:
                this.input_female_gender.setSelected(true);
                break;
            case MALE:
                this.input_male_gender.setSelected(true);
                break;
            default:
                this.input_other_gender.setSelected(true);
                break;
        }
        System.out.println(staff.toString());
    }
}
