package SubInterface;


import Main.Main;
import User.Staff.Staff;
import Interface.Interface_MenuManager;
import Interface.Interface_MenuStaff;


import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ITSUKA KOTORI
 */
public class SubInterface_Login_Staff extends javax.swing.JFrame {

    private int fail_time = 0;
    Staff logined_staff;
    boolean loged_in = false;
    /**
     * Creates new form LoginInterface
     */
    public SubInterface_Login_Staff() {
        initComponents();
        initComponents_SetClose();
        this.ok_button.setVisible(false);
        this.setIconImage(Main.DEFUALT_ICON.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        input_user_id = new javax.swing.JTextField();
        input_passord = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        error_message = new javax.swing.JLabel();
        ok_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Login");
        setResizable(false);

        login.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Staff ID                         :");

        input_user_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        input_user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_user_idActionPerformed(evt);
            }
        });
        input_user_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_user_idKeyReleased(evt);
            }
        });

        input_passord.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        input_passord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_passordActionPerformed(evt);
            }
        });
        input_passord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_passordKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Password                     :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_user_id, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(input_passord))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_user_id, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(input_passord, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        error_message.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        ok_button.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ok_button.setText("OK");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(error_message, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 26)); // NOI18N
        jLabel1.setText("Welcome !! Login As Staff");

        jLabel4.setForeground(new java.awt.Color(23, 184, 202));
        jLabel4.setText("Switch User");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initComponents_SetClose() {        
        setTitle("Staff or Manager Login Module");
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                
            }
        });
    }
    
    private String code_id(String source){
        //NMCHPARDO1234567890
        source = source.replace('N', 'Z');
        source = source.replace('C', 'Q');
        source = source.replace('H', '+');
        source = source.replace('P', '&');
        source = source.replace('A', '(');
        source = source.replace('R', '*');
        source = source.replace('1', '@');
        source = source.replace('2', '!');
        source = source.replace('3', '/');
        source = source.replace('4', '\\');
        source = source.replace('5', ']');
        source = source.replace('6', '{');
        source = source.replace('7', ' ');
        source = source.replace('8', '-');
        source = source.replace('9', '=');
        return source;
    }
    
    public static String decode_id(String source){
        source = source.replace('Z', 'N');
        source = source.replace('Q', 'C');
        source = source.replace('+', 'H');
        source = source.replace('&', 'P');
        source = source.replace('(', 'A');
        source = source.replace('*', 'R');
        source = source.replace('@', '1');
        source = source.replace('!', '2');
        source = source.replace('/', '3');
        source = source.replace('\\', '4');
        source = source.replace(']', '5');
        source = source.replace('{', '6');
        source = source.replace(' ', '7');
        source = source.replace('-', '8');
        source = source.replace('=', '9');
        return source;
    }
    
    public static void validate_login_go(Staff staff){
        if(staff != null && staff.isManager()){
            new Interface_MenuManager().setVisible(true);
        }else{
            new Interface_MenuStaff().setVisible(true);
        }
    }
    
    private void logined_true(){
        FileWriter fileWriter;
        this.set_all_background("#9ED9CC");
        this.loged_in = true;
        try {
            fileWriter = new FileWriter("resource/data/staff_id_logedin.txt");
            try (BufferedWriter buffer = new BufferedWriter(fileWriter)) {
                buffer.write(this.code_id(this.input_user_id.getText()) + "\n");
                buffer.flush();
                buffer.close();
                this.login.setVisible(false);
                this.cancel.setVisible(false);
                this.ok_button.setVisible(true);
                loged_in = true;
                this.error_message.setText("Logined to your account sucessful !!");
            }
        } catch (IOException ex) {
            Logger.getLogger(SubInterface_Login_Staff.class.getName()).log(Level.SEVERE, null, ex);
            this.input_user_id.setEditable(true);
            this.input_passord.setEditable(true);
            this.error_message.setText("Sorry the system has crash please restart proran!!");
        }
    }
    
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        this.input_user_id.setEditable(false);
        this.input_passord.setEditable(false);
        
        logined_staff = new Staff(this.input_user_id.getText());
        if(this.input_passord.getText().equals(logined_staff.getLogin_password())){
            logined_true();
        }else{
            fail_time++;
            this.set_all_background("#FFDDE2");
            this.error_message.setText("Login is incorrect, please enter the correct id or password");
            this.input_user_id.setEditable(true);
            this.input_passord.setEditable(true);
            if(fail_time > 3)
            {        
                this.dispose();
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.setVisible(false);
        this.dispose();
        this.set_all_background("#FFDDE2");
        this.error_message.setText("You had cancel the login process!!");
    }//GEN-LAST:event_cancelActionPerformed

    private void input_user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_user_idActionPerformed

    }//GEN-LAST:event_input_user_idActionPerformed

    private void input_user_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_user_idKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            input_passord.requestFocusInWindow();
        }
    }//GEN-LAST:event_input_user_idKeyReleased

    private void input_passordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_passordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_passordActionPerformed

    private void input_passordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_passordKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            loginActionPerformed(null);
        }
    }//GEN-LAST:event_input_passordKeyReleased

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        // TODO add your handling code here:
        validate_login_go(this.logined_staff);
        this.dispose();
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        this.dispose();
        new SubInterface_Login_Customer().setVisible(true);
    }//GEN-LAST:event_jLabel4MousePressed


    private void set_all_background(String hex_code){
        jPanel1.setBackground(Color.decode(hex_code));
        jPanel2.setBackground(Color.decode(hex_code));
        this.getContentPane().setBackground(Color.decode(hex_code));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel error_message;
    private javax.swing.JPasswordField input_passord;
    private javax.swing.JTextField input_user_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables
    
    
}
